# Generated by Django 5.0.3 on 2024-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_field',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
