# Generated by Django 5.0.3 on 2024-04-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_field',
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=8, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='article.article')),
            ],
        ),
    ]
