# Generated by Django 5.0.3 on 2024-04-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_date_field_articlelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleLink',
        ),
    ]
