# Generated by Django 5.0.4 on 2024-04-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_delete_articlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markdown_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
